version: "3"

services:

  web:

    image: httpd:latest
    container_name: apache_server
    ports:
      # host:container
      - 3080:80
    volumes:
      - /home/alberto/public/:/usr/local/apache2/htdocs/

      
      
